#!/usr/bin/env python3
# -*- coding: utf-8 -*-


# audio I/O: Whisper speech-to-text and gTTS text-to-speech.
# whisper and Pygame are initialized at import time (optional dependencies).


import io
from gtts import gTTS

#load Whisper for speech-to-text at import time.
try:
    import whisper
    whisper_model = whisper.load_model("base")
    print("✅ Whisper loaded successfully")
except Exception as e:
    whisper_model = None
    print(f"⚠️ Error loading Whisper: {e}")

#transcribe audio file to text using Whisper if available.
def transcribe_audio(audio_file):
    
    if audio_file is None:
        return "❌ No audio received", ""
    try:
        #check if Whisper is available
        if whisper_model is None:
            return "❌ Whisper not available. Install with: pip install openai-whisper", ""
        
        print(f"🎤 Transcribing audio: {audio_file}")

        #transcribe audio file to text
        result = whisper_model.transcribe(audio_file, language="en")
        #strip whitespace from transcribed text
        text   = result["text"].strip()

        if not text:
            return "❌ No text detected in audio", ""
        
        print(f"✅ Transcribed text: {text}")

        return f"🎤 Transcribed: {text}", text
    
    except Exception as e:
        print(f"❌ Transcription error: {e}")
        return f"❌ Error during transcription: {str(e)}", ""
    
#convert text to speech using gTTS and return audio data as bytes.
def text_to_speech(text, lang="en"):
    
    try:
        #validate input text, text.strip removes leading/trailing whitespace of the written text, and len checks if the phrase exists
        if not text or len(text.strip()) < 3:
            return None
        
        #creates a buffer in RAM memory for saving momentarily the audio data generated by gTTS
        buf = io.BytesIO()

        #convert text to speech
        tts = gTTS(text=text, lang=lang, slow=False)
        #save the generated speech audio to the buffer
        tts.write_to_fp(buf)
        #reset buffer position to the beginning before reading
        buf.seek(0)
        #read the audio data from the buffer and return it as bytes
        data = buf.read()
        #close the buffer to free up resources
        buf.close()
        #return the audio data as bytes
        return data
    
    except Exception as e:
        print(f"❌ Text-to-speech error: {e}")
        return None
